GET http://localhost:5237/empleados

###
GET http://localhost:5237/empleados/1

###
POST http://localhost:5237/empleados/
Content-Type: application/json

{
    "Nombre": "Julian",
    "Apellidos": "Alvarez 2",
    "PuestoId": 3,
    "Departamento": "Tecnología",
    "Salario": 4500,
    "FechaNacimiento": "1999-04-24"

}

###
PUT http://localhost:5237/empleados/6
Content-Type: application/json

{
    "Nombre": "David Davideti",
    "Apellidos": "Gimeno",
    "PuestoId": 2,
    "Departamento": "Desarrollo",
    "Salario": 2020,
    "FechaNacimiento": "2001-08-24"
  }

###
DELETE http://localhost:5237/empleados/4